import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.metrics.pairwise import rbf_kernel as sklearn_rbf_kernel # Keep for comparison/reference if needed
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.kernel_approximation import RBFSampler

def load_iris_data(): # Only numerical cols
  iris = load_iris(as_frame=True)
  data_df = iris.data
  target = iris.target

  # Handle missing values
  data_df = data_df.replace('?', np.nan)
  data_df = data_df.dropna()
  target = target.loc[data_df.index]

  le_target = LabelEncoder()
  y = le_target.fit_transform(target)

  # Split into training and validation sets (80% train, 20% validation)
  X_train, X_val, y_train, y_val = train_test_split(data_df, y, test_size=0.2, stratify=y)

  # Standardize numerical features
  scaler = StandardScaler()
  scaler.fit(X_train)
  X_train_processed = scaler.transform(X_train)
  X_val_processed = scaler.transform(X_val)

  print(f'Shapes of X_train: {X_train_processed.shape}, X_val: {X_val_processed.shape}')
  return X_train_processed, X_val_processed, y_train, y_val


def load_adult_data(subset_size=500):
  adult = fetch_openml('adult', version=2, as_frame=True)
  data_df = adult.data
  target = adult.target

  # Handle missing values
  data_df = data_df.replace('?', np.nan)
  data_df = data_df.dropna()
  target = target.loc[data_df.index]

  subset_indices = np.random.choice(len(data_df), subset_size, replace=False)
  data_df = data_df.iloc[subset_indices, :]
  target = target.iloc[subset_indices]

  # Encode target ('<=50K' and '>50K' to 0 and 1)
  le_target = LabelEncoder()
  y = le_target.fit_transform(target)

  # Split into training and validation sets (80% train, 20% validation)
  X_train, X_val, y_train, y_val = train_test_split(data_df, y, test_size=0.2, random_state=42, stratify=y)

  # Identify numerical and categorical columns
  numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
  categorical_cols = X_train.select_dtypes(include=['category']).columns
#   categorical_cols = []

  ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
  ohe.fit(X_train[categorical_cols])
  X_train_cat = ohe.transform(X_train[categorical_cols])
  X_val_cat = ohe.transform(X_val[categorical_cols])

  # Standardize numerical features
  scaler = StandardScaler()
  scaler.fit(X_train[numerical_cols])
  X_train_num = scaler.transform(X_train[numerical_cols])
  X_val_num = scaler.transform(X_val[numerical_cols])

  # Combine processed features
  X_train_processed = np.hstack((X_train_num, X_train_cat))
  X_val_processed = np.hstack((X_val_num, X_val_cat))

  print(f'Shapes of X_train: {X_train_processed.shape}, X_val: {X_val_processed.shape}')
  return X_train_processed, X_val_processed, y_train, y_val

def get_coreset_rff_sampler_log(X_train_np, m, kernel_gamma, n_rff_components=500, n_epochs=1000, lr=0.001, lambda_log=1e-4, epsilon=1e-6, random_seed=42):
    """
    Selects a coreset using MMD optimization with Random Fourier Features generated by sklearn.kernel_approximation.RBFSampler,
    using a non-convex log penalty for sparsity. Logs MMD^2 and loss over epochs.

    Args:
        X_train_np (np.ndarray): The full training dataset.
        m (int): The desired size of the coreset.
        kernel_gamma (float): The gamma parameter for the RBF kernel, used by RBFSampler.
        n_rff_components (int): Number of random Fourier features to approximate the kernel.
        n_epochs (int): Number of optimization epochs.
        lr (float): Learning rate for the Adam optimizer.
        lambda_log (float): Regularization strength for the log penalty.
        epsilon (float): Small constant for numerical stability in log penalty.
        random_seed (int): Seed for reproducibility.

    Returns:
        tuple: A tuple containing:
            - coreset_indices_np (np.ndarray): Indices of the selected coreset points.
            - weights_coreset_np (np.ndarray): Normalized weights for the selected coreset points.
            - mmd_history (list): List of MMD^2 values over the epochs.
            - loss_history (list): List of total loss values over the epochs.
    """
    torch.manual_seed(random_seed)
    np.random.seed(random_seed)  # RBFSampler uses numpy's random state

    mmd_history = []
    loss_history = []

    n = X_train_np.shape[0]
    if m > n:
        print(f"Warning: Coreset size m ({m}) is greater than dataset size n ({n}). Setting m = n.")
        m = n
    if m == 0:  # Handle edge case of requesting an empty coreset
        return np.array([], dtype=int), np.array([]), mmd_history, loss_history
    if n == 0:  # Handle edge case of empty input data
        print("Warning: Input data X_train_np is empty. Returning empty coreset.")
        return np.array([], dtype=int), np.array([]), mmd_history, loss_history

    # Initialize RBFSampler
    rbf_feature_map = RBFSampler(gamma=kernel_gamma, n_components=n_rff_components, random_state=random_seed)

    # Compute RFF features for the entire dataset using RBFSampler
    Z_train_np = rbf_feature_map.fit_transform(X_train_np)
    Z_train = torch.from_numpy(Z_train_np).float()  # Convert to PyTorch tensor

    # Initialize learnable logits for weights
    w_logits = nn.Parameter(torch.full((n,), 0.1, dtype=torch.float32, requires_grad=True))
    optimizer = optim.Adam([w_logits], lr=lr)

    # Compute MMD using RFF features
    mean_Z_full = torch.mean(Z_train, dim=0)  # Shape: (n_rff_components,)

    for epoch in range(n_epochs):
        optimizer.zero_grad()

        # Current positive weights from logits
        current_learned_weights = torch.relu(w_logits)

        # Normalize weights for MMD calculation (sum to 1)
        sum_current_learned_weights = current_learned_weights.sum()
        if sum_current_learned_weights < 1e-9:  # Effectively zero sum
            normalized_eval_weights = torch.zeros_like(current_learned_weights)
        else:
            normalized_eval_weights = current_learned_weights / sum_current_learned_weights

        # Compute E_Q[Z(Y)] for the coreset
        mean_Z_coreset = torch.sum(normalized_eval_weights.unsqueeze(1) * Z_train, dim=0)  # Shape: (n_rff_components,)

        # MMD^2 = ||E_P[Z(X)] - E_Q[Z(Y)]||^2
        mmd2_objective = torch.sum((mean_Z_full - mean_Z_coreset)**2)

        # Non-convex log penalty: sum(log(epsilon + w_i))
        log_penalty = lambda_log * torch.sum(torch.log(epsilon + current_learned_weights))

        # Total loss
        loss = mmd2_objective - log_penalty

        # Log MMD^2 and loss
        mmd_history.append(mmd2_objective.item())
        loss_history.append(loss.item())

        loss.backward()
        # torch.nn.utils.clip_grad_norm_(w_logits, max_norm=1.0)
        optimizer.step()

    # Get final sparse positive weights
    final_learned_weights = torch.relu(w_logits).detach()

    final_learned_weights_np = final_learned_weights.cpu().numpy()
    print('Top final weights:', np.sort(final_learned_weights_np)[::-1][:100])

    # Fallback if all learned weights are zero
    if final_learned_weights.sum() < 1e-9:
        print("Critical Warning: All learned weights are effectively zero. Coreset selection will be random for indices, with uniform weights.")
        coreset_indices_np = np.random.choice(n, m, replace=False) if n >= m else np.arange(n)
        weights_coreset_np = np.ones(len(coreset_indices_np)) / len(coreset_indices_np) if len(coreset_indices_np) > 0 else np.array([])
        return coreset_indices_np, weights_coreset_np.flatten(), mmd_history, loss_history

    # Select top m indices based on final_learned_weights
    k_topk = min(m, len(final_learned_weights))
    if k_topk == 0:
        return np.array([], dtype=int), np.array([]), mmd_history, loss_history

    top_k_selected_values, top_k_indices_torch = torch.topk(final_learned_weights, k=k_topk)
    coreset_indices_np = top_k_indices_torch.cpu().numpy()
    selected_coreset_weights_torch = top_k_selected_values.cpu()

    # Normalize selected weights to sum to 1
    sum_selected_coreset_weights = selected_coreset_weights_torch.sum()
    if sum_selected_coreset_weights < 1e-9:
        print(f"Warning: Top {k_topk} selected learned weights sum to near zero. Using uniform weights for the coreset.")
        weights_coreset_normalized_torch = torch.ones_like(selected_coreset_weights_torch) / k_topk if k_topk > 0 else torch.empty(0)
    else:
        weights_coreset_normalized_torch = selected_coreset_weights_torch / sum_selected_coreset_weights

    weights_coreset_np = weights_coreset_normalized_torch.numpy()

    return coreset_indices_np, weights_coreset_np.flatten(), mmd_history, loss_history


# --- Downstream Classification Model Training ---
def train_classifier(X_train: np.ndarray, X_val: np.ndarray, y_train: np.ndarray, y_val: np.ndarray) -> float:
    if len(np.unique(y_train)) < 2:
        print(f"  Warning: Training data for classifier contains only {len(np.unique(y_train))} unique class(es) (labels: {np.unique(y_train)}). Skipping training and returning NaN.")
        return np.nan
    clf = LogisticRegression(max_iter=1000, random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_val)
    acc = accuracy_score(y_val, y_pred)
    return acc


def calculate_mmd2_exact(X_full, X_coreset, coreset_weights, kernel_gamma):
    """
    Calculates the exact squared MMD between the full dataset and a coreset using the RBF kernel.

    Args:
        X_full (np.ndarray): The full dataset, shape (n, d).
        X_coreset (np.ndarray): The coreset, shape (m, d).
        coreset_weights (np.ndarray): Weights for the coreset points, shape (m,), summing to 1.
        kernel_gamma (float): The gamma parameter for the RBF kernel.

    Returns:
        float: The squared MMD value.
    """
    if len(X_coreset) == 0:
        return np.inf  # Return infinity if coreset is empty

    # Convert inputs to PyTorch tensors
    X_full_torch = torch.from_numpy(X_full).float()
    X_coreset_torch = torch.from_numpy(X_coreset).float()
    w_torch = torch.from_numpy(coreset_weights).float()

    n = X_full_torch.shape[0]  # Number of points in full dataset
    m = X_coreset_torch.shape[0]  # Number of points in coreset

    # Initialize accumulators
    sum_K_full = torch.tensor(0.0)  # Scalar for full dataset kernel sum
    sum_K_cross_per_j = torch.zeros(m)  # Vector for cross terms per coreset point

    # Compute sums iteratively
    for i in range(n):
        x_i = X_full_torch[i].unsqueeze(0)  # Shape (1, d)

        # Full dataset term: k(x_i, X_full)
        distances_full = torch.cdist(x_i, X_full_torch)  # Shape (1, n)
        k_full = torch.exp(-kernel_gamma * distances_full**2)  # Shape (1, n)
        sum_K_full += k_full.sum()  # Scalar

        # Cross term: k(x_i, X_coreset)
        distances_coreset = torch.cdist(x_i, X_coreset_torch)  # Shape (1, m)
        k_coreset = torch.exp(-kernel_gamma * distances_coreset**2).squeeze()  # Shape (m,)
        sum_K_cross_per_j += k_coreset  # Accumulate vector of size m

    # Coreset term: compute K_coreset matrix since m is small
    distances_coreset = torch.cdist(X_coreset_torch, X_coreset_torch)  # Shape (m, m)
    K_coreset = torch.exp(-kernel_gamma * distances_coreset**2)  # Shape (m, m)

    # Compute the three terms
    term1 = (1 / n**2) * sum_K_full  # E_{x,x' ~ P}[k(x, x')]
    term2 = w_torch @ K_coreset @ w_torch  # E_{y,y' ~ Q}[k(y, y')]
    term3 = -2 * (1 / n) * (sum_K_cross_per_j @ w_torch)  # -2 * E_{x ~ P, y ~ Q}[k(x, y)]

    # Total MMD squared
    mmd2 = term1 + term2 + term3

    return mmd2.item()

n_trials = 10
coreset_sizes = [10, 20, 30, 40, 50, 60, 70]


np.random.seed(666)

X_train_full, X_val, y_train_full, y_val = load_adult_data(2500)

acc_whole = train_classifier(X_train_full, X_val, y_train_full, y_val)

print(f"Baseline (whole dataset) accuracy: {acc_whole:.4f}\n")

# containers
accuracies = {
    'RBFSampler_Coreset': [],
    'Random': []
}

mmd_scores = {
    'RBFSampler_Coreset': [],
    'Random': []
}


# Number of random features for RBFSampler
n_rff_components = 40 # A common choice, can be tuned
kernel_gamma = 0.1 # Kernel gamma for MMD calculation

for coreset_size in coreset_sizes:
    m = max(1, coreset_size)
    print(f"Coreset size:→ m = {m} samples")

    # --- RBFSampler-Coreset multi-trial ---
    acc_coreset_trials = []
    mmd_coreset_trials = []

    coreset_idx, coreset_w, mmd_history, loss_history = get_coreset_rff_sampler_log(
            X_train_full, m,
            kernel_gamma=kernel_gamma,
            n_rff_components=n_rff_components,
            n_epochs=1000,
            lr=0.1,
            lambda_log=1e-9,
            epsilon= 1e-3,
            random_seed=42) # Vary seed for trials

    # plt.plot(loss_history[100:])
    # plt.xlabel('Epoch')
    # plt.ylabel('MMD^2')
    # plt.title('MMD^2 Over Epochs')
    # plt.grid(True)
    # plt.show()

    X_core = X_train_full[coreset_idx]
    y_core = y_train_full[coreset_idx]

    mmd_t = calculate_mmd2_exact(X_train_full, X_core, coreset_w, kernel_gamma)
    mmd_coreset_trials.append(mmd_t)

    acc_t = train_classifier(X_core, X_val, y_core, y_val)
    acc_coreset_trials.append(acc_t)

    print(acc_coreset_trials)


    mean_acc_core = np.mean(acc_coreset_trials)
    mean_mmd_core = np.mean(mmd_coreset_trials)
    accuracies['RBFSampler_Coreset'].append(mean_acc_core)
    mmd_scores['RBFSampler_Coreset'].append(mean_mmd_core)
    print(f" → RBFSampler Coreset Accuracy (mean over {n_trials} trials): {mean_acc_core:.4f}")
    print(f" → RBFSampler Coreset MMD^2 (mean over {n_trials} trials): {mean_mmd_core:.4f}")


    # --- Random-sampling multi-trial ---
    acc_rand_trials = []
    mmd_rand_trials = []
    for t in range(n_trials):
        np.random.seed(42 + t)
        idx = np.random.choice(len(X_train_full), m, replace=False)
        X_rand = X_train_full[idx]
        y_rand = y_train_full[idx]
        # For random sampling, weights are uniform
        weights_rand = np.ones(len(idx)) / len(idx)

        acc_random = train_classifier(X_rand, X_val, y_rand, y_val)
        acc_rand_trials.append(acc_random)

        mmd_rand = calculate_mmd2_exact(X_train_full, X_rand, weights_rand, kernel_gamma)
        mmd_rand_trials.append(mmd_rand)

    mean_acc_rand = np.mean(acc_rand_trials)
    mean_mmd_rand = np.mean(mmd_rand_trials)
    accuracies['Random'].append(mean_acc_rand)
    mmd_scores['Random'].append(mean_mmd_rand)
    print(f" → Random Sampling Accuracy (mean over {n_trials} trials): {mean_acc_rand:.4f}")
    print(f" → Random Sampling MMD^2 (mean over {n_trials} trials): {mean_mmd_rand:.4f}\n")


# ── Plotting Accuracy ──
plt.figure(figsize=(10,6))
plt.plot(coreset_sizes, accuracies['RBFSampler_Coreset'],
            marker='o', label='RBFSampler Coreset')
plt.plot(coreset_sizes, accuracies['Random'],
            marker='s', linestyle='--', label='Random Sampling')
plt.axhline(acc_whole, color='k', linestyle='-', label='Whole Dataset')
plt.xlabel('Coreset Size (m)')
plt.ylabel('Validation Accuracy')
plt.title('Mean Validation Acc vs. Coreset Size')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ── Plotting MMD ──
plt.figure(figsize=(10,6))
plt.plot(coreset_sizes, mmd_scores['RBFSampler_Coreset'],
            marker='o', label='RBFSampler Coreset (Weighted)')
plt.plot(coreset_sizes, mmd_scores['Random'],
            marker='s', linestyle='--', label='Random Sampling (Uniform Weights)')
plt.xlabel('Coreset Size (m)')
plt.ylabel('MMD²')
plt.title('MMD² vs. Coreset Size')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()